

<svelte:head>
	<title>{data.title.name}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">

  <meta property="og:title" content="PLay with GPT-3 AI">
  <meta property="og:type" content="website">
  <meta property="og:description" content="Try GPT-3 here.">
</svelte:head>


  <h1>PLay with GPT-3 AI</h1>
  <label for="prompt">Type what you want here:</label>
  <textarea name="prompt" id="prompt" placeholder="I am so cool..."></textarea>
